# Generated by Django 4.0.2 on 2022-03-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='due_date',
            field=models.TextField(),
        ),
    ]
